export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'

export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
export const UPDATE_TODO_FAILUER = 'UPDATE_TODO_FAILUER'

export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'

export const TOGGLE_EDIT_ID = 'TOGGLE_EDIT_ID'
export const CHANGE_NEW_DESCRIPTION = 'CHANGE_NEW_DESCRIPTION'
